#! /bin/bash
LOGDATE=$(date +%y%m%d)
printf "Memory\t\tDisk\t\tCPU\t\tHostname\t\tDate\n"
end=$((SECONDS+3600))
while [ $SECONDS -lt $end ]; do
MEMORY=$(free -m | awk 'NR==2{printf "%.2f%%\t\t", $3*100/$2 }')
DISK=$(df -h | awk '$NF=="/"{printf "%s\t\t", $5}')
CPU=$(top -bn1 | grep load | awk '{printf "%.2f%%\t\t\n", $(NF-2)}')
DATE=$(date +%Y-%m-%d:%H:%M:%S)
HOSTNAME=$(echo `ifconfig  2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'` | awk '{print $1}')
echo -e "$MEMORY$DISK$CPU$HOSTNAME\t\t$DATE" > /tmp/log$LOGDATE
sleep 5
done
                                                                              
